services:
  # 1. Layanan Database (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: portal_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portal_banking
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. Layanan Backend (Express.js)
  backend:
    container_name: portal_backend
    build: ./backend
    ports:
      - "8000:8000"
      - "5555:5555" # Port untuk Prisma Studio
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/portal_banking"
    volumes:
      # Ini adalah kunci "hot-reloading":
      # Menyinkronkan kode lokal Anda ke dalam container
      - ./backend/src:/usr/src/app/src
      - ./backend/prisma:/usr/src/app/prisma
    depends_on:
      - db # Backend baru akan start SETELAH 'db' service siap

  # 3. Layanan Frontend (Next.js)
  frontend:
    container_name: portal_frontend
    build: ./frontend
    ports:
      - "3001:3000"
    volumes:
      # Kunci "hot-reloading" untuk Next.js
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    depends_on:
      - backend

volumes:
  pgdata: # Volume untuk menyimpan data DB
