services:
  # 1. Layanan Database (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: portal_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portal_banking
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. Backend (Express.js)
  # backend:
  #   container_name: portal_backend
  #   build: ./backend
  #   ports:
  #     - "8000:8000"
  #     - "5555:5555" # Port Prisma Studio
  #   environment:
  #     DATABASE_URL: "postgresql://user:password@db:5432/portal_banking"
  #     NODE_ENV: "development"
  #   volumes:
  #     # Ini adalah kunci "hot-reloading":
  #     # Menyinkronkan kode lokal Anda ke dalam container
  #     - ./backend/src:/usr/src/app/src
  #     - ./backend/prisma:/usr/src/app/prisma
  #     - ./backend/package.json:/usr/src/app/package.json
  #     - ./backend/.env:/usr/src/app/.env
  #   depends_on:
  #     - db

  # # 3. Layanan Frontend (Next.js)
  # frontend:
  #   container_name: portal_frontend
  #   build: ./frontend
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     NODE_ENV: "development"
  #     NEXT_TELEMETRY_DISABLED: "1"
  #   volumes:
  #     # Kunci "hot-reloading" untuk Next.js
  #     - ./frontend/app:/usr/src/app/app
  #     - ./frontend/components:/usr/src/app/components
  #     - ./frontend/contexts:/usr/src/app/contexts
  #     - ./frontend/public:/usr/src/app/public
  #     - ./frontend/package.json:/usr/src/app/package.json
  #     # Tidak mount next.config.js untuk menghindari infinite loop
  #     - /usr/src/app/node_modules
  #     - /usr/src/app/.next
  #   depends_on:
  #     - backend

volumes:
  pgdata: # Volume untuk menyimpan data DB
